version: "3.5"

networks:
  online-store-network:
    name: online-store-network
    external: true

services:
  dev-frontend:
    container_name: dev-frontend
    build:
      context: .
      dockerfile: Dockerfile.dev
    image: s083r/latte-frontend:${IMAGE_TAG}
    restart: 'always'
    env_file:
      - .env
    networks:
      - online-store-network
