version: "3.5"

networks:
  online-store-network:
    name: iced-latte-network
    external: true

services:
  iced-latte-frontend:
    image: 'zufarexplainedit/iced-latte-frontend:${DOCKER_IMAGE_TAG}'
    container_name: iced-latte-frontend
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    restart: 'always'
    networks:
      - iced-latte-network


