name: CI/CD Pipeline for DEV environment

on:
  push:
    branches: [ development ]
  pull_request:
    types: [ closed ]

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}

jobs:
  setup-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Checkout private env repository
        uses: actions/checkout@v2
        with:
          repository: Sunagatov/Vault
          token: ${{ secrets.PRIVATE_REPO_ACCESS_TOKEN }}
          path: Vault

      - name: List files in IcedLatte/Frontend
        run: ls -lah Vault/IcedLatte/Frontend

      - name: Copy .env file
        run: cp ./Vault/IcedLatte/Frontend/.env ./

      - name: Load .env file
        uses: xom9ikk/dotenv@v2
        with:
          load-mode: strict

      - name: Set IMAGE_TAG
        run: echo "IMAGE_TAG=$GITHUB_REF_NAME-${GITHUB_SHA:0:7}" >> $GITHUB_ENV

      - name: Build the docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG -f Dockerfile.dev .

      - name: Log in to docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push image
        run: |
          docker push $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG

      - name: Deploy image via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.DEV_SSH_HOST }}
          port: ${{ secrets.DEV_SSH_PORT }}
          username: ${{ secrets.DEV_SSH_USER }}
          key: ${{ secrets.DEV_SSH_PRIV_KEY }}
          script: |
            docker pull $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
            docker stop dev-frontend || true
            docker rm dev-frontend || true
            docker run -d --name dev-frontend --network online-store-network --restart always --env-file .env $DOCKERHUB_USERNAME/$IMAGE_NAME:$IMAGE_TAG
