name: Build & deploy image

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:
    runs-on: self-hosted
#    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: 'Create env file'
      run: |
        echo "${{ secrets.ENV_FILE }}" > .env
    - name: Declare some variables
      shell: bash
      run: |
        echo "sha_short=$(git rev-parse --short "$GITHUB_SHA")" >> "$GITHUB_ENV"
        echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> "$GITHUB_ENV"
    - name: Another step
      run: |
        echo "Branch: ${{ env.branch }}"
        echo "Sha: ${{ env.sha_short }}"
    - name: Build the Docker image
      run: docker-compose -f docker-compose.dev.yml  build
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Push image
      run: docker push s083r/latte-frontend:dev-latest
